class UserExistsError(Exception):
    pass

class AuthError(Exception):
    pass